- name: Install 'Bareos' client
  hosts: all
  become: true
  become_user: exadmn
  vars:
    ansible_port: "{{ survey_ansible_port }}"
  tasks:
    - name: Identify Linux distribution
      set_fact:
        linux_distribution: "{{ ansible_facts['distribution'] | lower }}"

    - name: Download and configure 'Bareos' repository for 'CENTOS'' based distro
      get_url:
        url: https://download.bareos.org/current/EL_7/add_bareos_repositories.sh
        dest: /tmp/add_bareos_repositories.sh
      when: linux_distribution == 'centos'

    - name: Download and configure 'Bareos' repository for 'RHEL' based distro
      get_url:
        url: https://download.bareos.org/current/EL_8/add_bareos_repositories.sh
        dest: /tmp/add_bareos_repositories.sh
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux']

    - name: Change permission for the 'Bareos' script file
      become: true
      file:
        path: "/tmp/add_bareos_repositories.sh"
        mode: "0755"
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

    - name: Run the script add the repository
      become: true
      become_user: root
      command: "bash /tmp/add_bareos_repositories.sh"
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

    - name: Update 'YUM' package cache
      become: true
      become_user: root
      yum:
        update_cache: yes
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

    - name: Install 'Bareos' File Daemon
      become: true
      become_user: root
      yum:
        name: bareos-fd
        state: present
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

    - name: Download and configure 'Bareos' repository for 'DEBAIN' based distro
      get_url:
        url: https://download.bareos.org/current/xUbuntu_20.04/add_bareos_repositories.sh
        dest: /tmp/add_bareos_repositories.sh
      when: linux_distribution == 'ubuntu'

    - name: Change permission for the 'Bareos' script file
      become: true
      file:
        path: "/tmp/add_bareos_repositories.sh"
        mode: "0755"
      when: linux_distribution == 'ubuntu'

    - name: Run the script and answer the prompt
      become: true
      become_user: root
      expect:
        command: bash /tmp/add_bareos_repositories.sh
        responses:
          "File '/etc/apt/keyrings/bareos-experimental.gpg' exists. Overwrite? (y/N)": "y"
        timeout: 120
      when: linux_distribution == 'ubuntu'

    - name: Update APT package cache
      become: true
      become_user: root
      apt:
        update_cache: yes
      when: linux_distribution == 'ubuntu'

    - name: Install 'Bareos File-Daemon'
      become: true
      become_user: root
      apt:
        name: bareos
        state: present
      when: linux_distribution == 'ubuntu'

    - name: Configure 'Bareos Client' settings
      become: true
      become_user: root
      template:
        src: templates/client.conf.j2
        dest: /etc/bareos/bareos-fd.d/client/myself.conf

    - name: Configure 'Bareos Director' settings
      become: true
      become_user: root
      template:
        src: templates/director.conf.j2
        dest: /etc/bareos/bareos-fd.d/director/bareos-dir.conf

    - name: Download and extract 'TLS' files
      become: true
      become_user: root
      get_url:
        url: https://box110.exaservers.com/tls.tar.gz
        dest: /tmp/tls.tar.gz

    - name: Extract 'TLS' files to 'Bareos' directory
      become: true
      become_user: root
      ansible.builtin.unarchive:
        src: /tmp/tls.tar.gz
        dest: /etc/bareos/
        remote_src: yes

    - name: Set ownership of 'Bareos' directory
      become: true
      become_user: root
      file:
        path: /etc/bareos/
        owner: bareos
        group: bareos
        recurse: yes

    - name: Restart 'Bareos File-Daemon'
      become: true
      become_user: root
      service:
        name: bareos-fd
        state: restarted
