---
- name: Install bareos client
  hosts: all
  become: true
  gather_facts: true
  become_user: exadmn
  vars:
    ansible_port: "{{ survey_ansible_port }}"
  tasks:
    - name: Identify Linux distribution
      set_fact:
        linux_distribution: "{{ ansible_facts['distribution'] | lower }}"

    - name: Download and configure Bareos repository for rhel based distro
      get_url:
        url: https://download.bareos.org/current/EL_8/add_bareos_repositories.sh
        dest: /tmp/add_bareos_repositories.sh
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

    - name: change permission for the bareos script file
      file:
        path: "/tmp/add_bareos_repositories.sh"
        mode: "0755"
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

    - name: run the script add the repository
      command: "/tmp/add_bareos_repositories.sh"
      become_user: root
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

    - name: Install Bareos File Daemon
      yum:
        name: bareos-fd
        state: present
      become_user: root
      when: linux_distribution in ['rocky', 'almalinux', 'cloudlinux', 'centos']

    - name: Download and configure Bareos repository for debain based distro
      get_url:
        url: https://download.bareos.org/current/xUbuntu_22.04/add_bareos_repositories.sh
        dest: /etc/yum.repos.d/bareos.repo
      when: linux_distribution == 'ubuntu'

    - name: change permission for the bareos script file
      file:
        path: "/tmp/add_bareos_repositories.sh"
        mode: "0755"
      when: linux_distribution == 'ubuntu'

    - name: run the script add the repository
      command: "/tmp/add_bareos_repositories.sh"
      become_user: root
      when: linux_distribution == 'ubuntu'

    - name: Install Bareos File Daemon
      apt:
        name: bareos
        state: present
      become_user: root
      when: linux_distribution == 'ubuntu'

    - name: Print the password
      debug:
        msg: "this {{ cpwd }}"

    - name: Configure Bareos File Daemon settings
      template:
        src: templates/client.conf.j2
        dest: /etc/bareos/bareos-fd.d/client/myself.conf
      become_user: root

    - name: Configure Bareos Director settings
      template:
        src: templates/director.conf.j2
        dest: /etc/bareos/bareos-fd.d/director/bareos-dir.conf

    - name: Download and extract TLS files
      get_url:
        url: https://box110.exaservers.com/tls.tar.gz
        dest: /tmp/tls.tar.gz

    - name: Extract TLS files to Bareos directory
      ansible.builtin.unarchive:
        src: /tmp/tls.tar.gz
        dest: /etc/bareos/
        remote_src: yes
      notify: restart bareos-fd

    - name: Set ownership of Bareos directory
      file:
        path: /etc/bareos/
        owner: bareos
        group: bareos
        recurse: yes

    - name: restart bareos-fd
      service:
        name: bareos-fd
        state: restarted
